name = "name"
main = "dist/index.js"
compatibility_date = "2023-12-06"

[vars]
APPLICATION_ID = "APPLICATION_ID"
APPLICATION_PUBLIC_KEY = "APPLICATION_PUBLIC_KEY"
TOKEN = "TOKEN"

kv_namespaces = [{ binding = "KV", id = "ID" }]

d1_databases = [{ binding = "DB", name = "name", database_id = "ID" }]

[ai]
binding = "AI"
